import { describe, expect, it } from 'vitest';

import type { C4Diagram, C4Element, C4Model, C4Relationship } from '../src/present/c4.js';
import { label, toMermaid } from '../src/present/mermaid.js';
import { quote, toStructurizr } from '../src/present/structurizr.js';

function element(overrides: Partial<C4Element> & Pick<C4Element, 'id' | 'name' | 'kind'>): C4Element {
  return {
    technology: null,
    description: null,
    inference: false,
    group: null,
    groupInference: false,
    evidence: [],
    ...overrides,
  };
}

function relationship(
  overrides: Partial<C4Relationship> & Pick<C4Relationship, 'from' | 'to'>,
): C4Relationship {
  return {
    label: 'imports',
    count: 1,
    confidence: 'fact',
    evidence: [],
    ...overrides,
  };
}

function diagram(overrides: Partial<C4Diagram> & Pick<C4Diagram, 'level'>): C4Diagram {
  return {
    scope: null,
    title: 'A diagram',
    elements: [],
    relationships: [],
    notes: [],
    ...overrides,
  };
}

/** A one-container, two-component model, small enough to assert whole. */
function model(): C4Model {
  return {
    context: diagram({
      level: 'context',
      title: 'System context — shop',
      elements: [
        element({
          id: 'system',
          name: 'shop',
          kind: 'system',
          technology: 'java',
          evidence: [{ kind: 'run', label: '/repos/shop @ abc1234567', path: null, line: null }],
        }),
        element({
          id: 'datastore',
          name: 'Database',
          kind: 'datastore',
          description: '1 table(s) observed',
          evidence: [{ kind: 'node', label: 'orders', path: null, line: null }],
        }),
      ],
      relationships: [relationship({ from: 'system', to: 'datastore', label: 'maps_to' })],
      notes: ['No fact in this run identifies a person.'],
    }),
    container: diagram({
      level: 'container',
      title: 'Containers — shop',
      elements: [
        element({
          id: 'container_server',
          name: 'server',
          kind: 'container',
          technology: 'java',
          description: '2 package(s), 3 type(s)',
          evidence: [{ kind: 'node', label: 'server', path: null, line: null }],
        }),
      ],
      relationships: [],
    }),
    components: [
      diagram({
        level: 'component',
        scope: 'server',
        title: 'Components — server',
        elements: [
          element({ id: 'component_a', name: 'a', kind: 'component' }),
          element({
            id: 'component_b',
            name: 'b',
            kind: 'component',
            group: 'Ordering',
            groupInference: true,
          }),
        ],
        relationships: [
          relationship({
            from: 'component_a',
            to: 'component_b',
            label: 'imports',
            count: 4,
            evidence: [
              { kind: 'edge', label: 'imports a.A → b.B', path: 'src/a/A.java', line: 3 },
            ],
          }),
        ],
      }),
    ],
  };
}

describe('Mermaid output', () => {
  it('renders a context diagram exactly', () => {
    expect(toMermaid(model().context)).toBe(
      [
        'flowchart LR',
        '  %% System context — shop',
        '  %% Generated by stratigraph. Every box is an aggregation of parsed facts;',
        '  %% a dashed line is inferred, not observed.',
        '  system["shop<br/>[java]"]',
        '  datastore[("Database<br/>1 table(s) observed")]',
        '  system -->|"maps_to"| datastore',
        '  %% No fact in this run identifies a person.',
        '',
      ].join('\n'),
    );
  });

  it('puts a grouped component in a subgraph and marks an inferred group', () => {
    const out = toMermaid(model().components[0] as C4Diagram);
    expect(out).toContain('  component_a["a"]');
    expect(out).toContain('  subgraph group_Ordering["Ordering (inferred)"]');
    expect(out).toContain('    component_b["b"]');
    expect(out).toContain('  end');
  });

  it('draws an inferred relationship dashed and says so on the line', () => {
    const source = diagram({
      level: 'container',
      elements: [
        element({ id: 'a', name: 'a', kind: 'container' }),
        element({ id: 'b', name: 'b', kind: 'container' }),
      ],
      relationships: [
        relationship({ from: 'a', to: 'b', label: 'http_calls', confidence: 'inferred' }),
      ],
    });
    expect(toMermaid(source)).toContain('  a -.->|"http_calls (inferred)"| b');
  });

  it('marks a model-authored element as inference in the box itself', () => {
    const source = diagram({
      level: 'component',
      elements: [element({ id: 'x', name: 'Billing', kind: 'component', inference: true })],
    });
    expect(toMermaid(source)).toContain('  x["Billing<br/>(inferred)"]');
  });

  it('is stable: the same model renders the same bytes', () => {
    expect(toMermaid(model().context)).toBe(toMermaid(model().context));
  });
});

describe('Mermaid escaping', () => {
  it('escapes the hash first, so the entity codes it emits survive', () => {
    // A TypeScript fqn carries `#`, and every replacement here is a `#`-prefixed
    // entity code — escaping `#` last would mangle all of them.
    expect(label('a#b"c')).toBe('a#35;b#quot;c');
    expect(label('<script>')).toBe('#lt;script#gt;');
  });

  it('escapes a quote inside a real fqn', () => {
    const source = diagram({
      level: 'component',
      elements: [element({ id: 'x', name: 'src/app#Order"Service', kind: 'component' })],
    });
    expect(toMermaid(source)).toContain('  x["src/app#35;Order#quot;Service"]');
  });

  it('keeps a newline out of a comment', () => {
    const source = diagram({ level: 'context', title: 'a\nb', notes: ['one\ntwo'] });
    const out = toMermaid(source);
    expect(out).toContain('  %% a b');
    expect(out).toContain('  %% one two');
  });
});

describe('Structurizr output', () => {
  const dsl = toStructurizr(model());

  it('nests components inside their container inside the system', () => {
    expect(dsl).toContain('system = softwareSystem "shop"');
    expect(dsl).toContain('container_server = container "server" "2 package(s), 3 type(s)" "java"');
    expect(dsl).toContain('component_a = component "a"');
  });

  it('models the data store beside the system, not inside it', () => {
    expect(dsl).toContain('datastore = softwareSystem "Database" "1 table(s) observed"');
    expect(dsl).toContain('tags "Database"');
  });

  it('carries provenance into a properties block on every element', () => {
    expect(dsl).toContain('"stratigraph.evidence.1" "/repos/shop @ abc1234567"');
    expect(dsl).toContain('"stratigraph.authored_by" "algorithm"');
  });

  it('carries provenance, confidence and observation count on a relationship', () => {
    expect(dsl).toContain('component_a -> component_b "imports"');
    expect(dsl).toContain('"stratigraph.confidence" "fact"');
    expect(dsl).toContain('"stratigraph.observations" "4"');
    expect(dsl).toContain('"stratigraph.evidence.1" "imports a.A → b.B [src/a/A.java:3]"');
  });

  it('records the cluster a component was grouped into, and that a model named it', () => {
    expect(dsl).toContain('tags "Inferred Group"');
    expect(dsl).toContain('"stratigraph.cluster" "Ordering"');
  });

  it('emits one view per level, scoping the component view to its container', () => {
    expect(dsl).toContain('container system "Containers" "Containers — shop"');
    expect(dsl).toContain('component container_server "Components-server" "Components — server"');
  });

  it('joins the stated omissions onto the view description rather than losing them', () => {
    // A view has exactly one description, and a `description` statement inside
    // the block replaces the argument — so the two have to be one string.
    expect(dsl).toContain(
      'systemContext system "SystemContext" ' +
        '"System context — shop No fact in this run identifies a person."',
    );
    expect(dsl).not.toContain('\n            description ');
  });

  it('styles inference so it is visible in a renderer, not only in a caption', () => {
    expect(dsl).toContain('relationship "Inferred" {');
    expect(dsl).toContain('dashed true');
  });

  it('declares relationships once, at the level that has them', () => {
    // Structurizr implies the system-level line from the container-level one;
    // declaring both would draw every relationship twice.
    expect(dsl).not.toContain('system -> datastore');
  });

  it('falls back to context relationships when the run produced no containers', () => {
    const historyOnly = model();
    historyOnly.container.elements = [];
    historyOnly.components = [];
    expect(toStructurizr(historyOnly)).toContain('system -> datastore "maps_to"');
  });

  it('is stable: the same model renders the same bytes', () => {
    expect(toStructurizr(model())).toBe(dsl);
  });
});

describe('Structurizr escaping', () => {
  it('escapes backslashes before quotes, so an escape is not itself escaped', () => {
    expect(quote('a\\b')).toBe('"a\\\\b"');
    expect(quote('say "hi"')).toBe('"say \\"hi\\""');
    expect(quote('C:\\repo\\"x"')).toBe('"C:\\\\repo\\\\\\"x\\""');
  });

  it('flattens newlines, because the parser is line-oriented', () => {
    expect(quote('one\ntwo\r\nthree')).toBe('"one two  three"');
  });

  it('escapes a windows path in an evidence property', () => {
    const source = model();
    (source.context.elements[0] as C4Element).evidence = [
      { kind: 'file', label: 'A.java', path: 'C:\\repo\\A.java', line: 2 },
    ];
    expect(toStructurizr(source)).toContain(
      '"stratigraph.evidence.1" "A.java [C:\\\\repo\\\\A.java:2]"',
    );
  });
});
