import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { migrate, openDatabase, type Db } from '../src/db/database.js';
import { createRun } from '../src/db/run.js';
import { listRepoFiles } from '../src/files/inventory.js';
import { assignFileRoles, classifyPath, parseCheckAttr } from '../src/files/roles.js';
import { pathScope } from '../src/history/paths.js';

const NONE = { generated: false, vendored: false };

describe('classifyPath', () => {
  // Each row: path, expected role, expected rule. The rule is part of the
  // contract — it is the citation for the role (ADR-0030).
  it.each([
    ['package-lock.json', 'lockfile', 'name:package-lock.json'],
    ['web/yarn.lock', 'lockfile', 'name:yarn.lock'],
    ['pnpm-lock.yaml', 'lockfile', 'name:pnpm-lock.yaml'],
    ['gradle.lockfile', 'lockfile', 'name:gradle.lockfile'],
    ['package.json', 'manifest', 'name:package.json'],
    ['services/api/pom.xml', 'manifest', 'name:pom.xml'],
    ['build.gradle.kts', 'manifest', 'name:build.gradle.kts'],
    ['angular.json', 'manifest', 'name:angular.json'],
    ['tsconfig.app.json', 'manifest', 'name:tsconfig*.json'],
    ['mvnw', 'manifest', 'name:mvnw'],
    ['.mvn/wrapper/maven-wrapper.properties', 'manifest', 'path:.mvn/'],
    ['gradle/wrapper/gradle-wrapper.jar', 'manifest', 'path:gradle/wrapper/'],
    ['src/test/java/com/acme/pom.xml', 'manifest', 'name:pom.xml'],
    ['vendor/lib/thing.js', 'vendored', 'path:vendor/'],
    ['src/main/webapp/js/jquery.min.js', 'vendored', 'name:*.min.*'],
    ['target-sources/generated/Foo.java', 'generated', 'path:generated/'],
    [
      'src/main/resources/db/changelog/0001-init.xml',
      'migration',
      'path:db/changelog/',
    ],
    ['src/main/resources/db/migration/V1__init.sql', 'migration', 'path:db/migration/'],
    ['src/test/java/com/acme/FooTest.java', 'test', 'path:src/test/'],
    ['src/app/foo/foo.component.spec.ts', 'test', 'name:*.spec.*'],
    ['lib/foo.test.ts', 'test', 'name:*.test.*'],
    ['module/src/main/java/com/acme/FooIT.java', 'test', 'name:*IT.java'],
    ['src/main/java/com/acme/Foo.java', 'source', 'ext:.java'],
    ['src/main/kotlin/Foo.kt', 'source', 'ext:.kt'],
    ['src/app/foo/foo.component.ts', 'source', 'ext:.ts'],
    ['src/app/foo/foo.component.html', 'source', 'ext:.html'],
    ['src/app/foo/foo.component.scss', 'source', 'ext:.scss'],
    ['src/main/resources/queries/report.sql', 'source', 'ext:.sql'],
    ['README.md', 'docs', 'ext:.md'],
    ['LICENSE', 'docs', 'name:LICENSE'],
    ['src/assets/i18n/en.json', 'config', 'ext:.json'],
    ['src/main/resources/application.yml', 'config', 'ext:.yml'],
    ['.gitignore', 'config', 'name:.gitignore'],
    ['Dockerfile', 'config', 'name:Dockerfile'],
    ['src/assets/logo.png', 'asset', 'ext:.png'],
    ['bin/something', 'other', 'none'],
  ])('%s is %s', (path, role, rule) => {
    const got = classifyPath(path, NONE, () => null);
    expect({ role: got.role, rule: got.rule }).toEqual({ role, rule });
  });

  it('lets .gitattributes outrank every name rule', () => {
    // The repository saying what a file is beats any convention of ours.
    expect(classifyPath('src/main/java/Api.java', { generated: true, vendored: false }, () => null))
      .toMatchObject({ role: 'generated', rule: 'gitattributes:linguist-generated' });
    expect(classifyPath('web/lib/chart.js', { generated: false, vendored: true }, () => null))
      .toMatchObject({ role: 'vendored', rule: 'gitattributes:linguist-vendored' });
  });

  it('marks a source file generated by its header, citing the line', () => {
    const head = '// Copyright\n// Code generated by protoc. DO NOT EDIT.\npackage foo;\n';
    expect(classifyPath('src/main/java/Foo.java', NONE, () => head)).toEqual({
      role: 'generated',
      rule: 'header:DO NOT EDIT',
      line: 2,
    });
  });

  it('recognises @Generated on a class, but not a word that merely contains it', () => {
    const annotated = 'package a;\n\n@Generated("jooq")\npublic class T {}\n';
    expect(classifyPath('src/main/java/T.java', NONE, () => annotated)).toMatchObject({
      role: 'generated',
      line: 3,
    });
    const prose = 'package a;\n// the @GeneratedValue id strategy\nclass E {}\n';
    expect(classifyPath('src/main/java/E.java', NONE, () => prose).role).toBe('source');
  });

  it('only reads the header of source candidates', () => {
    // A lockfile is never opened: the name already decided it.
    let reads = 0;
    classifyPath('package-lock.json', NONE, () => {
      reads += 1;
      return null;
    });
    classifyPath('src/Foo.java', NONE, () => {
      reads += 1;
      return 'class Foo {}';
    });
    expect(reads).toBe(1);
  });
});

describe('parseCheckAttr', () => {
  it('reads git check-attr -z output, treating set and true alike', () => {
    const out = [
      'a.js', 'linguist-generated', 'true',
      'a.js', 'linguist-vendored', 'unspecified',
      'b.js', 'linguist-generated', 'unspecified',
      'b.js', 'linguist-vendored', 'set',
      'c.js', 'linguist-generated', 'false',
      'c.js', 'linguist-vendored', 'unset',
      '',
    ].join('\0');
    const attrs = parseCheckAttr(out);
    expect(attrs.get('a.js')).toEqual({ generated: true, vendored: false });
    expect(attrs.get('b.js')).toEqual({ generated: false, vendored: true });
    expect(attrs.get('c.js')).toEqual({ generated: false, vendored: false });
  });
});

describe('assignFileRoles', () => {
  let db: Db;
  let runId: number;
  let repo: string;

  beforeEach(() => {
    db = openDatabase(':memory:');
    migrate(db);
    repo = mkdtempSync(join(tmpdir(), 'stratigraph-roles-'));
    runId = createRun(db, repo).id;
  });

  afterEach(() => {
    db.close();
    rmSync(repo, { recursive: true, force: true });
  });

  function file(path: string, text: string): void {
    mkdirSync(dirname(join(repo, path)), { recursive: true });
    writeFileSync(join(repo, path), text);
  }

  it('writes one cited row per file, and is idempotent', () => {
    file('package-lock.json', '{}');
    file('src/main/java/Foo.java', 'class Foo {}\n');
    file('src/main/java/Gen.java', '// @generated\nclass Gen {}\n');
    const tracked = ['package-lock.json', 'src/main/java/Foo.java', 'src/main/java/Gen.java'];
    const attrs = () => new Map();

    assignFileRoles(db, runId, repo, tracked, attrs);
    const counts = assignFileRoles(db, runId, repo, tracked, attrs);

    expect(counts).toEqual({ lockfile: 1, source: 1, generated: 1 });
    expect(
      db.prepare('SELECT path, role, rule, line FROM file_role WHERE run_id = ? ORDER BY path').all(runId),
    ).toEqual([
      { path: 'package-lock.json', role: 'lockfile', rule: 'name:package-lock.json', line: null },
      { path: 'src/main/java/Foo.java', role: 'source', rule: 'ext:.java', line: null },
      { path: 'src/main/java/Gen.java', role: 'generated', rule: 'header:@generated', line: 1 },
    ]);
  });
});

describe('listRepoFiles', () => {
  function tree(files: Record<string, string>): string {
    const root = mkdtempSync(join(tmpdir(), 'stratigraph-inventory-'));
    for (const [path, text] of Object.entries(files)) {
      mkdirSync(dirname(join(root, path)), { recursive: true });
      writeFileSync(join(root, path), text);
    }
    return root;
  }

  it('lists tracked files in a git repository, and nothing untracked', () => {
    const root = tree({ 'src/A.java': 'class A {}', 'scratch.txt': 'x' });
    execFileSync('git', ['init', '-q'], { cwd: root });
    execFileSync('git', ['add', 'src/A.java'], { cwd: root });

    expect(listRepoFiles(root, pathScope([], []))).toEqual({
      source: 'git',
      files: ['src/A.java'],
    });
  });

  it('walks a directory that is not a repository, pruning excluded directories', () => {
    // No git is no reason to have no denominator: the coverage of a tarball
    // is as real as the coverage of a clone.
    const root = tree({
      'src/A.java': 'class A {}',
      'node_modules/x/index.ts': 'export {}',
      'web/app.ts': 'export {}',
    });

    expect(listRepoFiles(root, pathScope(['node_modules'], []))).toEqual({
      source: 'walk',
      files: ['src/A.java', 'web/app.ts'],
    });
  });

  it('applies include prefixes either way', () => {
    const root = tree({ 'src/A.java': 'class A {}', 'web/app.ts': 'export {}' });
    expect(listRepoFiles(root, pathScope([], ['web/'])).files).toEqual(['web/app.ts']);
  });
});

describe('classifyPath, by content and convention (ADR-0037, ADR-0030)', () => {
  const head = (text: string) => () => text;
  it.each([
    ['sql/eladmin.sql', 'CREATE TABLE `sys_user` (', 'migration', 'header:DDL'],
    ['conf/upgrade.sql', 'ALTER TABLE config_info ADD COLUMN x int;', 'migration', 'header:DDL'],
    ['src/main/resources/data.sql', "INSERT INTO owners VALUES (1, 'x');", 'source', 'ext:.sql'],
    ['invoice/src/main/resources/migration/V20190924__add.sql', 'select 1', 'migration', 'name:V*__*.sql'],
    ['api/src/main/resources/liquibase-schema-only.xml', '<databaseChangeLog xmlns="x">', 'migration', 'header:databaseChangeLog'],
    ['api/src/main/proto/service.proto', 'syntax = "proto3";', 'source', 'ext:.proto'],
    ['src/main/resources/schema/schema.graphqls', 'type Query {}', 'source', 'ext:.graphqls'],
    ['.env', '', 'config', 'name:.*'],
    ['lombok.config', '', 'config', 'ext:.config'],
    ['core/src/main/resources/META-INF/spring.factories', '', 'config', 'path:META-INF/'],
    ['NEWS', '', 'docs', 'name:NEWS'],
    ['resources/copyright', '', 'docs', 'name:copyright'],
    ['pnpm-workspace.yaml', '', 'manifest', 'name:pnpm-workspace.yaml'],
  ])('%s → %s', (path, text, expectedRole, expectedRule) => {
    expect(classifyPath(path, NONE, head(text))).toMatchObject({ role: expectedRole, rule: expectedRule });
  });
});

describe('classifyPath under a main source root', () => {
  it('reads a package named tests as main code', () => {
    expect(
      classifyPath('gateway-integration-tests/grpc/src/main/java/org/x/tests/grpc/GrpcApp.java', NONE, () => ''),
    ).toMatchObject({ role: 'source' });
    expect(classifyPath('module/src/test/java/org/x/AppTest.java', NONE, () => '')).toMatchObject({ role: 'test' });
  });
});

describe('classifyPath in a documentation tree', () => {
  it('reads a generated doc site as docs, and keeps its images assets', () => {
    expect(classifyPath('docs/index.html', NONE, () => '')).toMatchObject({ role: 'docs', rule: 'path:docs/' });
    expect(classifyPath('docs/modules/ROOT/assets/images/a.png', NONE, () => '')).toMatchObject({ role: 'asset' });
    expect(classifyPath('api/src/main/java/org/x/docs/Page.java', NONE, () => '')).toMatchObject({ role: 'source' });
  });
});
