#!/usr/bin/env bash
# Regenerates the Java extractor's complete package listings (ADR-0038) from
# framework jars in the local Maven cache. Output: one line per package,
# "package Type Type ...", top-level types only, sorted. Checked in; rerun when
# a listed framework gains types, and review the diff.
set -euo pipefail
M2="${M2:-$HOME/.m2/repository}"
OUT="extractors/java/src/main/resources/dev/stratigraph/extractor/java/known-packages.txt"
JARS=(
  jakarta/persistence/jakarta.persistence-api/3.1.0/jakarta.persistence-api-3.1.0.jar
  jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.jar
  com/fasterxml/jackson/core/jackson-annotations/2.21/jackson-annotations-2.21.jar
  org/projectlombok/lombok/1.18.46/lombok-1.18.46.jar
  org/springframework/spring-web/6.1.4/spring-web-6.1.4.jar
  org/springframework/spring-context/6.1.4/spring-context-6.1.4.jar
  org/springframework/spring-beans/6.1.4/spring-beans-6.1.4.jar
  org/springframework/spring-tx/6.1.4/spring-tx-6.1.4.jar
  org/springframework/data/spring-data-commons/3.2.3/spring-data-commons-3.2.3.jar
  org/springframework/data/spring-data-jpa/3.2.3/spring-data-jpa-3.2.3.jar
  org/springframework/security/spring-security-core/6.2.2/spring-security-core-6.2.2.jar
  org/springframework/security/spring-security-config/6.2.2/spring-security-config-6.2.2.jar
  org/springframework/security/spring-security-web/6.2.2/spring-security-web-6.2.2.jar
  org/springframework/boot/spring-boot/3.2.3/spring-boot-3.2.3.jar
  org/springframework/boot/spring-boot-autoconfigure/3.2.3/spring-boot-autoconfigure-3.2.3.jar
  org/hibernate/orm/hibernate-core/6.4.4.Final/hibernate-core-6.4.4.Final.jar
  io/swagger/swagger-annotations/1.6.14/swagger-annotations-1.6.14.jar
  io/swagger/core/v3/swagger-annotations-jakarta/2.2.19/swagger-annotations-jakarta-2.2.19.jar
)
tmp=$(mktemp)
for jar in "${JARS[@]}"; do
  unzip -Z1 "$M2/$jar" | grep -E '\.class$' | grep -v '\$' | grep -v -E '(package-info|module-info)\.class$' \
    | sed 's/\.class$//' | tr '/' '.' >> "$tmp"
done
# hibernate-core is huge; only its annotation package is ever wildcard-imported.
grep -v -E '^org\.hibernate\.' "$tmp" > "$tmp.keep" || true
grep -E '^org\.hibernate\.annotations\.[A-Za-z0-9_]+$' "$tmp" >> "$tmp.keep" || true
# javax.persistence / javax.validation: the jakarta APIs renamed. A superset of
# the javax names, which only ever makes a competing javax wildcard *more*
# ambiguous, never less.
grep -E '^jakarta\.(persistence|validation)\.' "$tmp.keep" | sed 's/^jakarta\./javax./' >> "$tmp.keep"
{
  echo "# Generated by scripts/gen-known-packages.sh — complete top-level type lists (ADR-0038)."
  awk '{ n = split($0, p, "."); cls = p[n]; pkg = substr($0, 1, length($0) - length(cls) - 1); print pkg, cls }' "$tmp.keep" \
    | sort -u | awk '{ if ($1 != cur) { if (cur != "") print line; cur = $1; line = $1 } line = line " " $2 } END { print line }'
} > "$OUT"
rm -f "$tmp" "$tmp.keep"
wc -l "$OUT"
