/**
 * Mermaid `flowchart` text for one C4 diagram.
 *
 * `flowchart` rather than Mermaid's own `C4Context` / `C4Container` blocks:
 * those are still marked experimental upstream, they render inconsistently
 * across the tools people actually paste diagrams into, and they have no way to
 * express "this line is a guess" — which is the one thing every output here has
 * to be able to say (ADR-0018).
 *
 * Mermaid has nowhere to put a citation, so this is the one output format that
 * drops evidence. ADR-0019 accepts that on the condition that the HTML report
 * shows the source next to the evidence rather than instead of it.
 */

import type { C4Diagram, C4Element, C4Relationship } from './c4.js';

/** Render one diagram. Deterministic: same model, same bytes. */
export function toMermaid(diagram: C4Diagram): string {
  const lines: string[] = [
    'flowchart LR',
    `  %% ${comment(diagram.title)}`,
    '  %% Generated by stratigraph. Every box is an aggregation of parsed facts;',
    '  %% a dashed line is inferred, not observed.',
  ];

  const grouped = new Map<string, C4Element[]>();
  const ungrouped: C4Element[] = [];
  for (const element of diagram.elements) {
    if (element.group === null) {
      ungrouped.push(element);
      continue;
    }
    const existing = grouped.get(element.group);
    if (existing) existing.push(element);
    else grouped.set(element.group, [element]);
  }

  for (const element of ungrouped) lines.push(`  ${node(element)}`);

  for (const [group, members] of grouped) {
    const inferred = members.some((member) => member.groupInference);
    lines.push(`  subgraph ${groupId(group)}["${label(group)}${inferred ? ' (inferred)' : ''}"]`);
    for (const member of members) lines.push(`    ${node(member)}`);
    lines.push('  end');
  }

  for (const relationship of diagram.relationships) lines.push(`  ${edge(relationship)}`);

  for (const note of diagram.notes) lines.push(`  %% ${comment(note)}`);

  return `${lines.join('\n')}\n`;
}

/**
 * A box, shaped by kind.
 *
 * The shapes are Mermaid's conventional ones — a cylinder for a store, a
 * rounded box for something outside the repository — so a reader who has never
 * used this tool still reads the diagram correctly.
 */
function node(element: C4Element): string {
  const parts = [label(element.name)];
  if (element.technology !== null) parts.push(`[${label(element.technology)}]`);
  if (element.description !== null) parts.push(label(element.description));
  if (element.inference) parts.push('(inferred)');
  const text = parts.join('<br/>');

  switch (element.kind) {
    case 'datastore':
      return `${element.id}[("${text}")]`;
    case 'external':
      return `${element.id}("${text}")`;
    case 'system':
      return `${element.id}["${text}"]`;
    default:
      return `${element.id}["${text}"]`;
  }
}

function edge(relationship: C4Relationship): string {
  const arrow = relationship.confidence === 'inferred' ? '-.->' : '-->';
  const text =
    relationship.confidence === 'inferred'
      ? `${relationship.label} (inferred)`
      : relationship.label;
  return `${relationship.from} ${arrow}|"${label(text)}"| ${relationship.to}`;
}

/**
 * Escape a label for a Mermaid quoted string.
 *
 * `#` goes first, because the replacements themselves are `#`-prefixed entity
 * codes and escaping it afterwards would mangle every one of them. A package
 * called `a"b` is not hypothetical in TypeScript, where an fqn carries a file
 * path.
 */
export function label(text: string): string {
  return text
    .replaceAll('#', '#35;')
    .replaceAll('"', '#quot;')
    .replaceAll('<', '#lt;')
    .replaceAll('>', '#gt;')
    .replaceAll('\n', ' ');
}

/** A comment runs to end of line, so the only thing that can break it is a newline. */
function comment(text: string): string {
  return text.replaceAll('\n', ' ');
}

function groupId(group: string): string {
  return `group_${group.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'x'}`;
}
