/**
 * Mermaid `flowchart` text for one C4 diagram.
 *
 * `flowchart` rather than Mermaid's own `C4Context` / `C4Container` blocks:
 * those are still marked experimental upstream, they render inconsistently
 * across the tools people actually paste diagrams into, and they have no way to
 * express "this line is a guess" — which is the one thing every output here has
 * to be able to say (ADR-0018).
 *
 * Mermaid has nowhere to put a citation, so this is the one output format that
 * drops evidence. ADR-0019 accepts that on the condition that the HTML report
 * shows the source next to the evidence rather than instead of it.
 */

import type { C4Diagram, C4Element, C4Relationship } from './c4.js';
import { shortName, type ClassDiagram } from './classes.js';
import type { ErCardinality, ErModel } from './erd.js';

/** Render one diagram. Deterministic: same model, same bytes. */
export function toMermaid(diagram: C4Diagram): string {
  const lines: string[] = [
    'flowchart LR',
    `  %% ${comment(diagram.title)}`,
    '  %% Generated by stratigraph. Every box is an aggregation of parsed facts;',
    '  %% a dashed line is inferred, not observed.',
  ];

  const grouped = new Map<string, C4Element[]>();
  const ungrouped: C4Element[] = [];
  for (const element of diagram.elements) {
    if (element.group === null) {
      ungrouped.push(element);
      continue;
    }
    const existing = grouped.get(element.group);
    if (existing) existing.push(element);
    else grouped.set(element.group, [element]);
  }

  for (const element of ungrouped) lines.push(`  ${node(element)}`);

  for (const [group, members] of grouped) {
    const inferred = members.some((member) => member.groupInference);
    lines.push(`  subgraph ${groupId(group)}["${label(group)}${inferred ? ' (inferred)' : ''}"]`);
    for (const member of members) lines.push(`    ${node(member)}`);
    lines.push('  end');
  }

  for (const relationship of diagram.relationships) lines.push(`  ${edge(relationship)}`);

  for (const note of diagram.notes) lines.push(`  %% ${comment(note)}`);

  return `${lines.join('\n')}\n`;
}

/**
 * A box, shaped by kind.
 *
 * The shapes are Mermaid's conventional ones — a cylinder for a store, a
 * rounded box for something outside the repository — so a reader who has never
 * used this tool still reads the diagram correctly.
 */
function node(element: C4Element): string {
  const parts = [label(element.name)];
  if (element.technology !== null) parts.push(`[${label(element.technology)}]`);
  if (element.description !== null) parts.push(label(element.description));
  if (element.inference) parts.push('(inferred)');
  const text = parts.join('<br/>');

  switch (element.kind) {
    case 'datastore':
      return `${element.id}[("${text}")]`;
    case 'external':
      return `${element.id}("${text}")`;
    case 'system':
      return `${element.id}["${text}"]`;
    default:
      return `${element.id}["${text}"]`;
  }
}

function edge(relationship: C4Relationship): string {
  const arrow = relationship.confidence === 'inferred' ? '-.->' : '-->';
  const text =
    relationship.confidence === 'inferred'
      ? `${relationship.label} (inferred)`
      : relationship.label;
  return `${relationship.from} ${arrow}|"${label(text)}"| ${relationship.to}`;
}

/**
 * A package's types as a Mermaid `classDiagram`.
 *
 * Generalisation and realisation get UML's own arrows (`<|--` and `<|..`), so
 * a reader can tell inheritance from a field reference without a legend.
 */
export function toClassMermaid(diagram: ClassDiagram): string {
  const lines: string[] = [
    'classDiagram',
    `  %% ${comment(`Types declared in ${diagram.packageFqn}`)}`,
    '  %% Generated by stratigraph. Every member was declared in the source.',
  ];

  for (const box of diagram.classes) {
    lines.push(`  class ${box.name} {`);
    const label = box.stereotype ?? (box.kind === 'class' ? null : box.kind);
    if (label !== null) lines.push(`    <<${label}>>`);
    for (const field of box.fields) lines.push(`    ${member(field.text)}`);
    for (const method of box.methods) lines.push(`    ${member(method.text)}`);
    lines.push('  }');
  }

  const names = new Map(diagram.classes.map((box) => [box.id, box.name]));
  for (const link of diagram.links) {
    const from = names.get(link.from);
    const to = names.get(link.to) ?? shortName(link.toFqn);
    if (from === undefined) continue;
    if (link.kind === 'extends') lines.push(`  ${to} <|-- ${from}`);
    else if (link.kind === 'implements') lines.push(`  ${to} <|.. ${from}`);
    else lines.push(`  ${from} --> ${to} : ${label(link.via ?? 'has')}`);
  }

  for (const note of diagram.notes) lines.push(`  %% ${comment(note)}`);
  return `${lines.join('\n')}\n`;
}

/**
 * A member line.
 *
 * Mermaid's class grammar is whitespace- and punctuation-sensitive inside a
 * block, so anything that could end the block early is removed rather than
 * escaped — there is no escape syntax to reach for.
 */
function member(text: string): string {
  return text.replaceAll('{', '(').replaceAll('}', ')').replaceAll('\n', ' ');
}

/**
 * Mermaid's crow's-foot notation for each cardinality we can read.
 *
 * Every one is "exactly one" on the certain side rather than "zero or one":
 * a `@ManyToOne` states the multiplicity and says nothing about nullability,
 * and `||` is the reading that does not assert what was not declared.
 */
const CROWS_FOOT: Record<ErCardinality, string> = {
  'many-to-one': '}o--||',
  'one-to-many': '||--o{',
  'one-to-one': '||--||',
  'many-to-many': '}o--o{',
};

/**
 * The ER model as a Mermaid `erDiagram`.
 *
 * Associations whose target could not be read appear as comments rather than
 * as lines to a guessed table — a diagram is not the place to soften a refusal
 * (ADR-0022).
 */
export function toErMermaid(model: ErModel): string {
  const lines: string[] = [
    'erDiagram',
    '  %% Generated by stratigraph from declared O/R mappings.',
  ];

  for (const entity of model.entities) {
    lines.push(`  ${identifier(entity.table)} {`);
    for (const column of entity.columns) {
      const marks = [column.primaryKey ? 'PK' : '', column.inherited ? '"inherited"' : '']
        .filter(Boolean)
        .join(' ');
      lines.push(
        `    ${identifier(column.type)} ${identifier(column.name)}${marks === '' ? '' : ` ${marks}`}`,
      );
    }
    lines.push('  }');
  }

  for (const relationship of model.relationships) {
    lines.push(
      `  ${identifier(relationship.fromTable)} ${CROWS_FOOT[relationship.cardinality]} ` +
        `${identifier(relationship.toTable)} : "${label(relationship.via)}"`,
    );
  }

  for (const association of model.unreadable) {
    lines.push(
      `  %% ${comment(
        `${association.fromTable}.${association.via} declares a ${association.cardinality} ` +
          `relationship, not drawn: ${association.reason}`,
      )}`,
    );
  }
  for (const note of model.notes) lines.push(`  %% ${comment(note)}`);

  return `${lines.join('\n')}\n`;
}

/**
 * A bare Mermaid identifier: no quotes, so nothing but word characters.
 *
 * Column names and SQL types are usually already safe; a name that is not gets
 * substituted rather than quoted, because Mermaid's ER grammar accepts a
 * quoted attribute name in some versions and not others.
 */
function identifier(text: string): string {
  return text.replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '') || 'unnamed';
}

/**
 * Escape a label for a Mermaid quoted string.
 *
 * `#` goes first, because the replacements themselves are `#`-prefixed entity
 * codes and escaping it afterwards would mangle every one of them. A package
 * called `a"b` is not hypothetical in TypeScript, where an fqn carries a file
 * path.
 */
export function label(text: string): string {
  return text
    .replaceAll('#', '#35;')
    .replaceAll('"', '#quot;')
    .replaceAll('<', '#lt;')
    .replaceAll('>', '#gt;')
    .replaceAll('\n', ' ');
}

/** A comment runs to end of line, so the only thing that can break it is a newline. */
function comment(text: string): string {
  return text.replaceAll('\n', ' ');
}

function groupId(group: string): string {
  return `group_${group.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'x'}`;
}
