/**
 * A Structurizr workspace covering all three levels.
 *
 * Unlike Mermaid, the DSL has somewhere to put provenance — every element and
 * every relationship gets a `properties` block naming the rows it came from —
 * so this is the one diagram format that carries its citations with it
 * (ADR-0019). A reader who opens the workspace in Structurizr can click an
 * element and see the file and line it was read from.
 *
 * The workspace is one hierarchical model with three views over it, rather than
 * three separate documents, because that is what Structurizr's own tooling
 * expects: containers live inside the software system, components inside their
 * container, and the higher-level relationships are implied from the lower
 * ones.
 */

import type { C4Diagram, C4Element, C4Model, C4Relationship, Evidence } from './c4.js';

const INDENT = '    ';

/** Render the whole model as one `workspace { … }` document. */
export function toStructurizr(model: C4Model): string {
  const out = new Writer();
  const system = model.context.elements.find((element) => element.kind === 'system');
  /* c8 ignore next */
  const systemName = system?.name ?? 'repository';

  out.line(
    `workspace ${quote(systemName)} ${quote(
      'Generated by stratigraph from parsed facts and git history.',
    )} {`,
  );
  out.indent();

  out.line('model {');
  out.indent();
  writeSystem(out, model, systemName);
  writeOuterElements(out, model.context);
  writeRelationships(out, model);
  out.dedent();
  out.line('}');

  out.blank();
  out.line('views {');
  out.indent();
  writeViews(out, model);
  writeStyles(out);
  out.dedent();
  out.line('}');

  out.dedent();
  out.line('}');
  return out.toString();
}

/**
 * The software system, its containers, and each container's components.
 *
 * Components are nested inside the container their packages belong to, which is
 * what makes a `component` view possible at all — Structurizr scopes that view
 * to one container.
 */
function writeSystem(out: Writer, model: C4Model, systemName: string): void {
  const system = model.context.elements.find((element) => element.kind === 'system');
  out.line(`system = softwareSystem ${quote(systemName)} ${quote(description(system))} {`);
  out.indent();
  if (system !== undefined) writeProperties(out, system.evidence, system.inference);

  for (const container of model.container.elements) {
    if (container.kind !== 'container') continue;
    const components = model.components.find(
      (diagram) => diagram.scope !== null && idOf(diagram) === container.id,
    );

    out.line(
      `${container.id} = container ${quote(container.name)} ${quote(
        description(container),
      )} ${quote(container.technology ?? '')} {`,
    );
    out.indent();
    writeProperties(out, container.evidence, container.inference);
    for (const component of components?.elements ?? []) {
      out.line(
        `${component.id} = component ${quote(component.name)} ${quote(
          description(component),
        )} ${quote(component.technology ?? '')} {`,
      );
      out.indent();
      if (component.group !== null) {
        out.line(`tags ${quote(component.groupInference ? 'Inferred Group' : 'Group')}`);
      }
      writeProperties(out, component.evidence, component.inference, component.group);
      out.dedent();
      out.line('}');
    }
    out.dedent();
    out.line('}');
  }

  out.dedent();
  out.line('}');
}

/**
 * Data stores and external systems, as software systems beside ours.
 *
 * A database is not in the source tree, and neither is `api.example.com`, so
 * neither belongs inside the system's boundary. Modelling them as siblings is
 * also what makes them appear in both the context and container views without
 * being declared twice.
 */
function writeOuterElements(out: Writer, context: C4Diagram): void {
  for (const element of context.elements) {
    if (element.kind !== 'datastore' && element.kind !== 'external') continue;
    out.line(
      `${element.id} = softwareSystem ${quote(element.name)} ${quote(description(element))} {`,
    );
    out.indent();
    out.line(`tags ${quote(element.kind === 'datastore' ? 'Database' : 'External')}`);
    writeProperties(out, element.evidence, element.inference);
    out.dedent();
    out.line('}');
  }
}

/**
 * Relationships, declared at the lowest level that has them.
 *
 * Structurizr implies a system-level relationship from a container-level one,
 * so declaring both would duplicate every line. The context relationships are
 * written only when this run produced no containers at all — which happens on a
 * history-only run, where there is nothing else to draw.
 */
function writeRelationships(out: Writer, model: C4Model): void {
  const hasContainers = model.container.elements.some((element) => element.kind === 'container');
  const diagrams: C4Diagram[] = hasContainers
    ? [model.container, ...model.components]
    : [model.context];

  for (const diagram of diagrams) {
    for (const relationship of diagram.relationships) {
      writeRelationship(out, relationship);
    }
  }
}

function writeRelationship(out: Writer, relationship: C4Relationship): void {
  const inferred = relationship.confidence === 'inferred';
  const label = inferred ? `${relationship.label} (inferred)` : relationship.label;
  out.line(`${relationship.from} -> ${relationship.to} ${quote(label)} {`);
  out.indent();
  if (inferred) out.line(`tags ${quote('Inferred')}`);
  out.line('properties {');
  out.indent();
  out.line(`${quote('stratigraph.confidence')} ${quote(relationship.confidence)}`);
  out.line(`${quote('stratigraph.observations')} ${quote(String(relationship.count))}`);
  writeEvidenceLines(out, relationship.evidence);
  out.dedent();
  out.line('}');
  out.dedent();
  out.line('}');
}

/** The provenance block. Every element gets one; a claim with no evidence is not publishable. */
function writeProperties(
  out: Writer,
  evidence: Evidence[],
  inference: boolean,
  group: string | null = null,
): void {
  out.line('properties {');
  out.indent();
  out.line(`${quote('stratigraph.authored_by')} ${quote(inference ? 'model' : 'algorithm')}`);
  if (group !== null) out.line(`${quote('stratigraph.cluster')} ${quote(group)}`);
  writeEvidenceLines(out, evidence);
  out.dedent();
  out.line('}');
}

function writeEvidenceLines(out: Writer, evidence: Evidence[]): void {
  for (const [n, item] of evidence.entries()) {
    const where =
      item.path === null ? '' : ` [${item.path}${item.line === null ? '' : `:${item.line}`}]`;
    out.line(`${quote(`stratigraph.evidence.${n + 1}`)} ${quote(`${item.label}${where}`)}`);
  }
}

function writeViews(out: Writer, model: C4Model): void {
  out.line(`systemContext system ${quote('SystemContext')} ${quote(caption(model.context))} {`);
  out.indent();
  out.line('include *');
  out.line('autolayout lr');
  out.dedent();
  out.line('}');

  const hasContainers = model.container.elements.some((element) => element.kind === 'container');
  if (hasContainers) {
    out.blank();
    out.line(`container system ${quote('Containers')} ${quote(caption(model.container))} {`);
    out.indent();
    out.line('include *');
    out.line('autolayout lr');
    out.dedent();
    out.line('}');
  }

  for (const diagram of model.components) {
    if (diagram.elements.length === 0) continue;
    out.blank();
    out.line(
      `component ${idOf(diagram)} ${quote(viewKey(diagram))} ${quote(caption(diagram))} {`,
    );
    out.indent();
    out.line('include *');
    out.line('autolayout lr');
    out.dedent();
    out.line('}');
  }
}

/**
 * The view's description: its title, then its stated omissions.
 *
 * The two are joined rather than declared separately because a view has exactly
 * one description — a `description` statement inside the block silently
 * replaces the argument, so writing both loses the title. The omissions travel
 * here rather than being dropped, because "no person appears on this diagram,
 * and here is why" is the part of a C4 context diagram this tool most wants a
 * reader to see (ADR-0019), and the description is what a renderer prints
 * underneath.
 */
function caption(diagram: C4Diagram): string {
  return [diagram.title, ...diagram.notes].join(' ');
}

function writeStyles(out: Writer): void {
  out.blank();
  out.line('styles {');
  out.indent();
  for (const [selector, rules] of [
    ['element "Software System"', ['background #1f6feb', 'color #ffffff', 'shape RoundedBox']],
    ['element "Container"', ['background #388bfd', 'color #ffffff', 'shape RoundedBox']],
    ['element "Component"', ['background #58a6ff', 'color #0d1117', 'shape RoundedBox']],
    ['element "Database"', ['background #6e7681', 'color #ffffff', 'shape Cylinder']],
    ['element "External"', ['background #8b949e', 'color #ffffff', 'shape RoundedBox']],
    // Inference has to be visible in the rendering, not only in a caption.
    ['element "Inferred Group"', ['border dashed', 'color #d29922']],
    ['relationship "Inferred"', ['dashed true', 'color #d29922']],
  ] as Array<[string, string[]]>) {
    out.line(`${selector} {`);
    out.indent();
    for (const rule of rules) out.line(rule);
    out.dedent();
    out.line('}');
  }
  out.dedent();
  out.line('}');
}

/** The container id a component diagram belongs to. */
function idOf(diagram: C4Diagram): string {
  /* c8 ignore next */
  const scope = diagram.scope ?? '';
  return `container_${scope.replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'root'}`;
}

function viewKey(diagram: C4Diagram): string {
  /* c8 ignore next */
  const scope = diagram.scope ?? 'root';
  return `Components-${scope.replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'root'}`;
}

function description(element: C4Element | undefined): string {
  if (element === undefined) return '';
  const parts: string[] = [];
  if (element.description !== null) parts.push(element.description);
  if (element.inference) parts.push('(name and description are model-authored inference)');
  return parts.join(' ');
}

/**
 * A DSL string literal.
 *
 * The DSL quotes with `"` and escapes with a backslash, so both have to be
 * escaped in that order, and a newline has to go — the parser is line-oriented
 * and a raw one would end the statement in the middle of a value.
 */
export function quote(text: string): string {
  const escaped = text
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\n', ' ')
    .replaceAll('\r', ' ');
  return `"${escaped}"`;
}

/** Deterministic indentation, so two runs of the same model are byte-identical. */
class Writer {
  private readonly lines: string[] = [];
  private depth = 0;

  line(text: string): void {
    this.lines.push(`${INDENT.repeat(this.depth)}${text}`);
  }

  blank(): void {
    this.lines.push('');
  }

  indent(): void {
    this.depth += 1;
  }

  dedent(): void {
    this.depth = Math.max(0, this.depth - 1);
  }

  toString(): string {
    return `${this.lines.join('\n')}\n`;
  }
}
